# Hadolint configuration for AI RPG Generator Dockerfile
# https://github.com/hadolint/hadolint#configure

failure-threshold: warning
format: tty  # Can be: tty, json, checkstyle, codeclimate, gitlab_codeclimate

# Ignore rules that don't apply to our development container
ignored:
  - DL3008  # Pin package versions (OK for dev containers with latest tools)
  - DL3009  # Delete apt cache (handled by --no-install-recommends)
  - DL3015  # Avoid additional packages (OK for comprehensive dev env)
  - SC2016  # Expressions in single quotes (intentional for script generation)

# Override severity levels for our use case
override:
  warning:
    - DL3059  # Multiple consecutive RUN instructions (important for layer optimization)
  error:
    - DL3020  # Use COPY instead of ADD (security)
    - DL3002  # Last USER should not be root (security)

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - registry.hub.docker.com

# Additional rules for our Rust environment
strictlabels: false  # Allow flexible labeling

# Custom rules for development containers
inline-threshold: info
